name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  Check_backend_tests_and_style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./puttipeliBackEnd

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run lint
        
      - name: run tests
        run: npm run test
  
  Check_frontend_tests_and_style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./puttipeliFrontEnd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      
      - name: Check style
        run: npm run lint


    