# Placeholder for when app goes live
name: Healthcheck pipeline

on:
  schedule:
    # Everyday at 16:00
    - cron: "0 16 * * *"

jobs:
  Healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: basic healthcheck
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://puttipeli.onrender.com/health
